# Generated by Django 4.0.1 on 2022-01-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_qq'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
