# Generated by Django 4.0.1 on 2022-02-04 22:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hd_study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('read_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('praise_count', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '后端学习',
                'verbose_name_plural': '后端学习',
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='练字分享文字内容')),
                ('image', models.ImageField(upload_to='practice_images', verbose_name='练字图片')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '练字分享',
                'verbose_name_plural': '练字分享',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='标题')),
                ('introduce', models.CharField(blank=True, max_length=70, verbose_name='引言')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('read_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '关于学习',
                'verbose_name_plural': '关于学习',
            },
        ),
        migrations.CreateModel(
            name='StudyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(max_length=30, verbose_name='姓名')),
                ('comment', models.CharField(max_length=200, verbose_name='评论')),
                ('agree', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.study', verbose_name='文章')),
            ],
            options={
                'verbose_name': '关于学习评论',
                'verbose_name_plural': '关于学习评论',
            },
        ),
    ]
