# Generated by Django 4.0.1 on 2022-02-04 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_created_time_alter_user_image_and_more'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycomment',
            name='user',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
